// src/types/personnel.ts (ou utilisateurs.ts)
import type { RoleType } from '../config/menuConfig'; // Réutiliser RoleType

export type { RoleType }; // Re-export RoleType to make it available for imports

export type StatutCompteUtilisateur = 'actif' | 'inactif' | 'bloque';

export interface UtilisateurSysteme {
  id?: string; // Make id optional since it's not required for creation (generated by Directus)
  prenom: string;
  nom: string;
  nomComplet?: string; // Propriété calculée pour affichage
  email: string; // Sera l'identifiant de connexion principal
  telephone?: string;
  roles: RoleType[]; // Un utilisateur peut potentiellement avoir plusieurs rôles (ex: polyvalent)
  statutCompte: StatutCompteUtilisateur;
  derniereConnexion?: string; // ISO Date string
  dateCreation?: string;
  // Ne pas stocker le mot de passe en clair ici !
}

export interface RecapPerformanceEmploye {
  employeId: string;
  nomComplet: string;
  rolePrincipal: 'pompiste' | 'caissier' | 'chef_de_piste' | 'polyvalent'; // Son rôle de base
  rolesTenusSurPeriode?: string[]; // Ex: ['Pompiste', 'Caissier'] si polyvalent
  nombreQuartsTravailles: number;
  nombreRetards: number;
  nombreAbsencesJustifiees: number;
  nombreAbsencesNonJustifiees: number;
  totalHeuresTravaillees?: number; // Calculé
  chiffreAffairesTotal: number; // XAF
  volumeTotalVendu?: number; // Litres (pour pompistes)
  uniteVolume?: 'L';
  nombreTotalTransactions: number;
  venteMoyenneParTransaction?: number; // CA / Nb Transactions
}

export interface DetailQuartTravailleEmploye {
  dateQuart: string; // YYYY-MM-DD
  typeQuartLibelle: string; // Ex: "Matin (07h-15h)"
  heureArriveeEnregistree?: string; // HH:mm
  heureDepartEnregistree?: string; // HH:mm
  statutPresence: 'Present' | 'Retard' | 'Absent_J' | 'Absent_NJ'; // J=Justifié, NJ=Non Justifié
  caGenereQuart?: number;
  volumeVenduQuart?: number;
  uniteVolume?: 'L';
}

export interface EmployeSimple {
  id: string;
  nomComplet: string;
  rolePrincipal: string;
}